spring:
  mvc:
    async:
      request-timeout: -1
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 30000
      lettuce:
        pool:
          max-active: 20
          max-idle: 5
          max-wait: -1
          min-idle: 0

logging:
  level:
    org.springframework.data.redis: DEBUG